POST http://localhost:3003/api/users/ HTTP/1.1
Content-type: application/json

{
  "username": "Mak2",
  "name": "Matti Luukkainen",
  "password": "mluukkai",
  "blogs": "66dd47a4c5933046dfa4617e" 
}